version: "3.8"
services:
  db:
    restart: always
    image: postgres:12.3
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "esmerald"
    expose:
      - "5432"
    volumes:
      - "esmerald:/var/lib/postgresql/data"
    command: >-
        --jit=false
    ports:
      - "5432:5432"

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    expose:
      - "6379"

volumes:
  esmerald:
    external: true
